# Generated by Django 4.2.6 on 2023-12-02 08:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_doctor_prescription_rename_address_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='advice',
            field=models.CharField(default='no specific advice', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(default='no specific medicine given', max_length=500),
        ),
    ]
