# Generated by Django 4.2.6 on 2023-12-15 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_doctor_name_alter_doctor_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient'),
        ),
    ]
