# Generated by Django 4.2.6 on 2024-03-11 06:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_rename_doctor_name_appointment_doctor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 11), null=True),
        ),
    ]
