# Generated by Django 4.2.6 on 2024-03-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_prescription_doctor_id_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.CharField(default='no specific medicine given', max_length=250),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='no specific medicine given', max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(default='no specific medicine given', max_length=100),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(default='no specific medicine given', max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
