# Generated by Django 4.2.6 on 2024-04-11 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_prescription_appointment_id_prescription_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(choices=[('9.30-10.30', '9.30-10.30'), ('10.30-11.30', '10.30-11.30')], default=datetime.date(2024, 4, 11), null=True),
        ),
    ]
