# Generated by Django 4.2.6 on 2023-12-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_entries',
            name='entry_time',
            field=models.DateTimeField(),
        ),
    ]
